INSERT INTO answers (school_id, user_id, question_id, content) VALUES
(1, 1, 1, 'This is the answer for question 1'),
(1, 2, 1, 'This is the second answer for question 1'),
(2, 1, 2, 'This is the answer for question 2'),
(2, 2, 2, 'This is the second answer for question 2'),
(3, 1, 3, 'This is the answer for question 3'),
(3, 2, 3, 'This is the second answer for question 3'),
(4, 1, 4, 'This is the answer for question 4'),
(4, 2, 4, 'This is the second answer for question 4'),
(5, 1, 5, 'This is the answer for question 5'),
(5, 2, 5, 'This is the second answer for question 5'),
(6, 1, 6, 'This is the answer for question 6'),
(6, 2, 6, 'This is the second answer for question 6'),
(7, 1, 7, 'This is the answer for question 7'),
(7, 2, 7, 'This is the second answer for question 7'),
(8, 1, 8, 'This is the answer for question 8'),
(8, 2, 8, 'This is the second answer for question 8'),
(9, 1, 9, 'This is the answer for question 9'),
(9, 2, 9, 'This is the second answer for question 9'),
(10, 1, 10, 'This is the answer for question 10'),
(10, 2, 10, 'This is the second answer for question 10'),
(11, 1, 11, 'This is the answer for question 11'),
(11, 2, 11, 'This is the second answer for question 11'),
(12, 1, 12, 'This is the answer for question 12'),
(12, 2, 12, 'This is the second answer for question 12'),
(13, 1, 13, 'This is the answer for question 13'),
(13, 2, 13, 'This is the second answer for question 13')
