# The name of the workflow
name: CI/CD for SchoolCompare

# This workflow will run on any push to the repository
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    # Set up the virtual machine for testing
    runs-on: ubuntu-latest

    services:
      # Configure PostgreSQL service
      postgres:
        image: postgres:13
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_DB: school_compare_springboot_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        # Give PostgreSQL some time to initialize
        options: >-
          --health-cmd="pg_isready -d school_compare_springboot_test"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5


    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Set Test Environment Variables
        run: |
          echo "OKTA_CLIENT_ID=${{ secrets.OKTA_CLIENT_ID }}" >> $GITHUB_ENV # Use a test API URL
          echo "OKTA_CLIENT_SECRET=${{ secrets.OKTA_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "OKTA_ISSUER=${{ secrets.OKTA_ISSUER }}" >> $GITHUB_ENV          

      - name: Verify environment variables
        run: |
          echo "OKTA_CLIENT_ID=$OKTA_CLIENT_ID"
          echo "OKTA_CLIENT_SECRET=$OKTA_CLIENT_SECRET"
          echo "OKTA_ISSUER=$OKTA_ISSUER"

      # Run tests with maven
      - name: Build with Maven
        run: mvn clean verify

      - name: Run tests
        env:
          SPRING_PROFILES_ACTIVE: test
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/school_compare_springboot_test
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: postgres
        run: mvn test