# The name of the workflow
name: CI/CD for SchoolCompare

# This workflow will run on any push to the repository
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    # Set up the virtual machine for testing
    runs-on: ubuntu-latest
    container: node:20-bookworm-slim

    services:
      # Configure PostgreSQL service
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: school_compare_springboot_test
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        # Give PostgreSQL some time to initialize
        options: >-
          --health-cmd pg_isready
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5


    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set Test Environment Variables
        run: |
          echo "OKTA_CLIENT_ID=${{ secrets.OKTA_CLIENT_ID }}" >> $GITHUB_ENV # Use a test API URL
          echo "OKTA_CLIENT_SECRET=${{ secrets.OKTA_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "OKTA_ISSUER=${{ secrets.OKTA_ISSUER }}" >> $GITHUB_ENV          

      - name: Verify environment variables
        run: |
          echo "OKTA_CLIENT_ID=$OKTA_CLIENT_ID"
          echo "OKTA_CLIENT_SECRET=$OKTA_CLIENT_SECRET"
          echo "OKTA_ISSUER=$OKTA_ISSUER"


      # Run tests with maven
      - name: Connect to PostgreSQL
        # Runs a script that creates a PostgreSQL table, populates
        # the table with data, and then retrieves the data.
        run: node client.js
        # Environment variables used by the `client.js` script to create a new PostgreSQL table.
        env:
          # The hostname used to communicate with the PostgreSQL service container
          POSTGRES_HOST: postgres
          # The default PostgreSQL port
          POSTGRES_PORT: 5432
      - name: Test with maven
        run: |
          mvn spring-boot:run & sleep 25 ; mvn test
        env:
          # The hostname used to communicate with the PostgreSQL service container
          POSTGRES_HOST: postgres
          # The default PostgreSQL port
          POSTGRES_PORT: 5432